-- Synthetic only: no application migrations or copied member data.
CREATE TABLE public.members (
  id integer PRIMARY KEY,
  label text NOT NULL,
  metadata jsonb,
  joined_at timestamptz NOT NULL
);
CREATE TABLE public.events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id integer REFERENCES public.members(id),
  title text NOT NULL,
  price numeric(10,2)
);
CREATE TABLE public.empty_items (id integer PRIMARY KEY);
CREATE SCHEMA proof_extra;
CREATE TABLE proof_extra.notes (body text, flag boolean);

INSERT INTO public.members VALUES
  (3, 'Synthetic Γ', '{"tags":[],"active":false}', '2025-01-03T12:00:00Z'),
  (1, 'Synthetic Alpha', '{"active":true,"tags":["one","two"]}', '2025-01-01T12:00:00Z'),
  (2, 'Synthetic Beta', NULL, '2025-01-02T12:00:00Z');
INSERT INTO public.events (member_id, title, price) VALUES
  (1, 'Fixture one', 0.00), (2, 'Fixture two', 12.50), (NULL, 'Fixture three', NULL);
-- Includes duplicates, NULL, Unicode and escaped newline/quotes, without a PK.
INSERT INTO proof_extra.notes VALUES
  (E'line one\nline "two"', true), ('duplicate', false),
  ('duplicate', false), (NULL, NULL);
